[phases.setup]
aptPkgs = ["libheif-dev", "libvips-dev", "fonts-liberation", "fontconfig"]

[phases.install]
cmds = ["npm ci", "npm rebuild sharp --from-source"]

[phases.build]
cmds = ["npm run build", "fc-cache -fv"]
